name: Build

on:
  push:
    paths:
      - packages/**
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - packages/**
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=sha,prefix={{branch}}-,event=branch,enable={{is_default_branch}}
            type=sha,prefix=temp-{{branch}}-,event=branch,enable=${{ github.ref != format('refs/heads/{0}', 'main') }}
            type=ref,prefix=temp-,suffix=-{{sha}},event=pr
            type=ref,event=tag
      - name: Set build version
        run: echo "BUILD_VERSION=${{ steps.meta.outputs.version }}" >> $GITHUB_ENV
      - name: Save PR metadata for CD workflow
        if: github.event_name == 'pull_request'
        run: |
          mkdir -p ./pr-metadata
          echo "{\"number\":\"${{ github.event.pull_request.number }}\", \"version\":\"${{ steps.meta.outputs.version }}\"}" > ./pr-metadata/pr-metadata.json
          
      - name: Upload PR metadata
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: pr-metadata
          path: ./pr-metadata
